### ISSUE TITLE
wikia.exe -update -lang pt

### ISSUE THREAD

**Issue by natanprog** [adrianojn/wikia#1]
```
wikia.exe -update -lang pt
loading Category:TCG cards
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.catch(0x33b70118, 0x1176e240)
        D:/src/github.com/adrianojn/wikia/util.go:42 +0x44
main.getListOfPages(0x0, 0x0, 0x0)
        D:/src/github.com/adrianojn/wikia/pages.go:51 +0x70a
main.wikia()
        D:/src/github.com/adrianojn/wikia/wikia.go:38 +0x29
main.main()
        D:/src/github.com/adrianojn/wikia/main.go:66 +0x1f7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1662 +0x1

goroutine 8 [IO wait]:
net.runtime_pollWait(0xc754f8, 0x72, 0x11748130)
        c:/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x116d7250, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*ioSrv).ExecIO(0x116e0628, 0x116d71b8, 0x6d0230, 0x7, 0x756adc, 0x44a870, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:182 +0x122
net.(*netFD).Read(0x116d7180, 0x11739000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:463 +0x129
net.(*conn).Read(0x116e0638, 0x11739000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:172 +0xb9
net/http.noteEOFReader.Read(0xc75570, 0x116e0638, 0x1172370c, 0x11739000, 0x1000, 0x1000, 0x641260, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1370 +0x55
net/http.(*noteEOFReader).Read(0x116c9540, 0x11739000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
        <autogenerated>:126 +0xae
bufio.(*Reader).fill(0x116c4e70)
        c:/go/src/bufio/bufio.go:97 +0x172
bufio.(*Reader).Peek(0x116c4e70, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xad
net/http.(*persistConn).readLoop(0x117236e0)
        c:/go/src/net/http/transport.go:876 +0xe3
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xabc

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0x117236e0)
        c:/go/src/net/http/transport.go:1009 +0x303
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xadc

goroutine 20 [select]:
net/http.(*persistConn).readLoop(0x1174e1e0)
        c:/go/src/net/http/transport.go:976 +0x8e8
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xabc

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0x1174e1e0)
        c:/go/src/net/http/transport.go:1009 +0x303
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xadc
```

@adrianojn

**Comment by adrianojn** [comment]
A URL da Wikia estava desatualizada, atualize o repositório e tente de novo.
